pipe_kwargs:
  pipe_device: cuda:0
vlm_kwargs:
  vlm_device: cuda:0
opt_kwargs:
  save_weights: True
  opt_cls: torch.optim.AdamW
  num_opt_steps: 100
  eval_every_n: ${opt_kwargs.num_opt_steps}
  train_seed: 100
  train_weight: 5
  optimizer_kwargs:
    weight_decay: 0
eval_kwargs:
  low_memory: True
  eval_seed: 0
  eval_weights:
    - 0
    - ${opt_kwargs.train_weight}
  eval_n: 5
lora_kwargs:
  r: 16
  lora_lr: 5e-5
  init_lora_weights: gaussian
  lora_dropout: 0.0